
import { Product, Category } from './types';

export const CATEGORIES: Category[] = [
  'All',
  'Paper Napkins',
  'Toilet Tissue Roll',
  'Facial Tissue',
  'Kitchen Rolls',
  'Kitchen Towels',
  'HRT Rolls',
  'GRT Rolls',
  'Bed Rolls',
  'Multi Fold Towels',
  'L-Fold Napkin',
];

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Royal Class 2 Ply Plain Napkin',
    category: 'Paper Napkins',
    description: "Soft, strong & perfectly plain for everyday use. Durable 2-ply napkins for all occasions.",
    imageUrl: 'https://beeimg.com/images/a07479024172.jpg',
  },
  {
    id: 2,
    name: 'Royal Class 2 Ply Printed Napkin',
    category: 'Paper Napkins',
    description: "Soft, durable & stylishly printed for every occasion. A touch of class for your table.",
    imageUrl: 'https://beeimg.com/images/a57858965371.jpg',
  },
  {
    id: 3,
    name: 'Royal Class 2 Ply Puff Printed Napkin',
    category: 'Paper Napkins',
    description: 'High-quality puff printed napkins that add elegance and texture to any setting.',
    imageUrl: 'https://beeimg.com/images/b40307231274.jpg',
  },
  {
    id: 4,
    name: 'Rose Touch 2 Ply Velvet Napkin',
    category: 'Paper Napkins',
    description: 'Experience the luxurious, velvet-soft feel of our premium napkins for special occasions.',
    imageUrl: 'https://beeimg.com/images/b48662009111.jpg',
  },
  {
    id: 5,
    name: 'Pack of 100 Soft Napkin 1 Ply',
    category: 'Paper Napkins',
    description: 'Embossed to provide a bulky, soft feel with the strength to tackle even the messiest meals.',
    imageUrl: 'https://beeimg.com/images/c84392321994.jpg',
  },
  {
    id: 6,
    name: 'Party Pack Napkin 1 Ply 100 Pulls',
    category: 'Paper Napkins',
    description: 'Perfect for every celebration & gathering. Convenient, stylish, and reliable.',
    imageUrl: 'https://beeimg.com/images/f40935420692.jpg',
  },
  {
    id: 7,
    name: 'L-Fold Table Top Tissue',
    category: 'L-Fold Napkin',
    description: '100 sheets of convenient L-fold napkins, perfect for dispensers and table tops.',
    imageUrl: 'https://beeimg.com/images/f51230381541.jpg',
  },
  {
    id: 8,
    name: 'Paper Bed Rolls',
    category: 'Bed Rolls',
    description: 'Disposable sheet material to cover examination tables, massage tables, and spa beds to maintain hygiene.',
    imageUrl: 'https://beeimg.com/images/g37809303181.jpg',
  },
  {
    id: 9,
    name: 'HRT Roll Embossed',
    category: 'HRT Rolls',
    description: 'High-performance, highly absorbent paper towels for commercial and institutional settings.',
    imageUrl: 'https://beeimg.com/images/i17835884232.jpg',
  },
  {
    id: 10,
    name: 'Kitchen Roll 4 Ply (200 Gms)',
    category: 'Kitchen Rolls',
    description: 'Strong & highly absorbent 4-ply kitchen roll for everyday use, made from towel grade paper.',
    imageUrl: 'https://beeimg.com/images/i58850019681.jpg',
  },
  {
    id: 11,
    name: 'Kitchen Roll 4 Ply (Pack of 3)',
    category: 'Kitchen Rolls',
    description: 'A value pack of three ultra-absorbent and long-lasting kitchen towels with superior strength.',
    imageUrl: 'https://beeimg.com/images/j89998485693.jpg',
  },
  {
    id: 12,
    name: 'Washable Kitchen Towel',
    category: 'Kitchen Towels',
    description: 'Reusable and strong kitchen towels, highly absorbent for all your cleaning needs.',
    imageUrl: 'https://beeimg.com/images/j99763821253.jpg',
  },
  {
    id: 13,
    name: 'GRT Roll',
    category: 'GRT Rolls',
    description: 'Heavy-duty paper towel rolls for kitchens and bathrooms, ideal for cleaning spills and surfaces.',
    imageUrl: 'https://beeimg.com/images/l12730344912.jpg',
  },
  {
    id: 14,
    name: 'Multi Fold Hand Towel',
    category: 'Multi Fold Towels',
    description: '100% Virgin Paper multi-fold towels, perfect for dispensers in high-traffic restrooms.',
    imageUrl: 'https://beeimg.com/images/l76386609162.jpg',
  },
  {
    id: 15,
    name: 'Regular Ultra Soft Facial Tissue',
    category: 'Facial Tissue',
    description: '100% Virgin Paper. Soft & gentle facial tissue made from premium imported paper. Qty-100 Pulls 2 Ply.',
    imageUrl: 'https://beeimg.com/images/m11199659971.jpg',
  },
  {
    id: 16,
    name: 'Pack of 6 Bathroom Toilet Paper Roll',
    category: 'Toilet Tissue Roll',
    description: 'Delicate, durable & essential bathroom tissue. Experience everyday freshness and a lasting clean.',
    imageUrl: 'https://beeimg.com/images/q76241373564.jpg',
  },
  {
    id: 17,
    name: 'Pack of 10 Toilet Paper Roll',
    category: 'Toilet Tissue Roll',
    description: 'Made from virgin chlorine-free paper. Soft on skin, dissolves quickly when flushed.',
    imageUrl: 'https://beeimg.com/images/s15464960163.jpg',
  },
  {
    id: 18,
    name: 'High-Quality Toilet Rolls (Embossed)',
    category: 'Toilet Tissue Roll',
    description: 'Imported paper toilet tissue roll with an elegant embossed pattern. Soft, strong, and absorbent.',
    imageUrl: 'https://beeimg.com/images/s75239963943.jpg',
  }
];